<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
  <TargetFramework>net48</TargetFramework>
  <LangVersion>latest</LangVersion>
  <VALHEIM_INSTALL>D:\SteamLibrary\steamapps\common\Valheim</VALHEIM_INSTALL>
  <BEPINEX_PATH>C:\Users\aaron\AppData\Roaming\r2modmanPlus-local\Valheim\profiles\BackShield\BepInEx</BEPINEX_PATH>
  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  <Nullable>disable</Nullable>
  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
</PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(BEPINEX_PATH)\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BEPINEX_PATH)\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(VALHEIM_INSTALL)\valheim_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(VALHEIM_INSTALL)\valheim_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(VALHEIM_INSTALL)\valheim_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>$(VALHEIM_INSTALL)\valheim_Data\Managed\assembly_valheim.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>$(VALHEIM_INSTALL)\valheim_Data\Managed\assembly_utils.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

<!-- this copies the compiled DLL automatically to r2modman's plugins folder -->
  <Target Name="AutoCopyDLL" AfterTargets="Build">
    <Copy SourceFiles="$(TargetDir)$(TargetFileName)" DestinationFolder="$(BEPINEX_PATH)\plugins" />
    <Message Text="=== MOD COPIED AUTOMATICALLY TO R2MODMAN! ===" Importance="high" />
  </Target>

</Project>